### ISSUE TITLE
Heatmap performance improvements

### ISSUE THREAD

**Issue by gis727** [GoogleCloudPlatform/flaky-service#144]
The heatmap should fetch all builds for a specific day only when the user selects a day (not when the heatmap initializes).
This will require a new endpoint in the API and a refactoring of the current build-fetching endpoint.
So:
`api/repo/:orgname/:reponame/batches` would return all batches for a repo.
`/api/repo/:orgname/:reponame/batch/:timestamp` would return every build for the timestamp day.

Batches would be:

interface {
- **timestamp**: number,
- **failingBuilds**: number, `// # of failling builds for the day`
- **flakyBuilds**: number, `// ...`
- **passingBuilds**: number, `// ...`

}

**Comment by bcoe** [comment]
@StuartRucker @gis727 I think what we'll probably want to do is pre-calculate the heat map, which just includes passed/failed counts on a given day, and an indication on a given day, if any of the tests at that point in time were considered flaky. Then, when someone clicks a given day, make a different API call that pulls in all the builds for that day.
