### ISSUE TITLE
allow an individual test to be deleted, by verifying identity with GitHub OAuth 2.0 dance

### ISSUE THREAD

**Issue by bcoe** [GoogleCloudPlatform/flaky-service#148]
@cedpeters we'll need to coordinate with @madelyndubuk to see where we should display the delete button, I imagine it would be in the expanded UX for tests eventually (see: https://github.com/GoogleCloudPlatform/flaky-service/pull/129).

@madelyndubuk, this isn't a blocker for landing #129, just me thinking about where the button should eventually live.

**Comment by cedpeters** [comment]
Sounds good, thanks Ben!
