### ISSUE TITLE
build listing component behaves "weird" when multiple pages of builds exist

### ISSUE THREAD

**Issue by bcoe** [GoogleCloudPlatform/flaky-service#177]
## Observed Behavior

_I noticed this testing [flaky-dashboard.web.app/org/GoogleCloudPlatform/flaky-service](https://flaky-dashboard.web.app/org/GoogleCloudPlatform/flaky-service)._

When multiple pages of builds exist, scrolling does not load new build data until you've scrolled completely through the previous result set, such that the component is a white background with no builds.

<img width="235" alt="Screen Shot 2020-07-28 at 3 35 40 PM" src="https://user-images.githubusercontent.com/194609/88729133-04d0bc00-d0e8-11ea-9a5d-f863f8f7402d.png">

When you scroll further, builds are inserted at the top:

<img width="232" alt="Screen Shot 2020-07-28 at 3 35 43 PM" src="https://user-images.githubusercontent.com/194609/88729149-0d28f700-d0e8-11ea-9de1-11b32de8b45f.png">

## Expected Behavior

it would be good to figure out a way to make the scrolling feel a bit smoother.

**Comment by gis727** [comment]
On it !
