### ISSUE TITLE
list of builds indicates all builds are healthy, on GitHub build indicates failure

### ISSUE THREAD

**Issue by bcoe** [GoogleCloudPlatform/flaky-service#180]
## Observed Behavior

The UX for `/org/GoogleCloudPlatform/flaky-service` indicates that all builds are green:

<img width="207" alt="Screen Shot 2020-07-29 at 10 34 10 AM" src="https://user-images.githubusercontent.com/194609/88833459-2339c480-d187-11ea-860e-1f27b07292a4.png">

However, when I visit the build on GitHub `186156771`, it indicates that there were some failures:

<img width="383" alt="Screen Shot 2020-07-29 at 10 36 00 AM" src="https://user-images.githubusercontent.com/194609/88833595-5419f980-d187-11ea-8843-4ffd02df985b.png">

## Expected Behavior

There have been a couple failed builds over the past week, I was surprised we don't see  any failures in the build list.

**Comment by bcoe** [comment]
@StuartRucker this might just be a request to check the database.

**Comment by StuartRucker** [comment]
I believe this was a symptom of the server not being able to handle mutiple posts with the same run_id. Before this pull request https://github.com/GoogleCloudPlatform/flaky-service/pull/149 which I hypothesize fixed the issue, you will notice that there is only one build for each id. However, if you click on one of the more recent dates, there are duplicate build ids listed under a particular time.
