### ISSUE TITLE
Empty description displayed as "None"

### ISSUE THREAD

**Issue by gis727** [GoogleCloudPlatform/flaky-service#213]
## Observed behavior
An empty description on a repository in displayed as **None**.

![Screenshot 2020-08-03 at 10 30 35 PM](https://user-images.githubusercontent.com/66028195/89246353-f5b2a800-d5d8-11ea-8e41-43e71ae5f403.png)

## Expected behavior
The description should be empty.

## Possible solution
Use an empty string instead of None in the action definition.
![Screenshot 2020-08-03 at 10 33 36 PM](https://user-images.githubusercontent.com/66028195/89246567-62c63d80-d5d9-11ea-87e0-88fffaad9d7e.png)

**Comment by StuartRucker** [comment]
This was done intentionally in src/post-build.js to avoid any Firestore issues with setting a key to an empty string. 

`description: metadata.github.event.repository.description || 'None'`

I will think about a better method, like possibly deleting the value if it is none before sending to UI
